# Generated by Django 3.2.2 on 2021-05-15 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Pizza', 'Pizza'), ('Sides', 'Sides'), ('Drinks', 'Drinks')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=128)),
                ('categary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.categary')),
                ('size', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.productsize')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('incart', 'incart'), ('placed', 'placed'), ('ontheway', 'ontheway'), ('delevered', 'delevered')], max_length=20)),
                ('item', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='pizza.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
