# Generated by Django 3.2.2 on 2021-05-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20210515_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=250, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
