# Generated by Django 3.2.2 on 2021-05-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_pasta_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza_type',
            name='categery',
            field=models.CharField(choices=[('Bestsellers', 'Bestsellers'), ('Classic', 'Classic'), ('Favourite', 'Favourite'), ('Delight', 'Delight')], default='Delight', max_length=20, verbose_name='Categery'),
        ),
    ]
