# Generated by Django 3.2.2 on 2021-05-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestdeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Deal Offer')),
                ('item', models.ManyToManyField(to='pizza.Product')),
            ],
        ),
    ]
