# Generated by Django 3.2.2 on 2021-05-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_bestdeal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestdeal',
            old_name='item',
            new_name='items',
        ),
        migrations.AddField(
            model_name='bestdeal',
            name='image',
            field=models.ImageField(default='static/images/bg_1.png', upload_to='static/images/bestdeals'),
        ),
        migrations.AddField(
            model_name='bestdeal',
            name='price',
            field=models.ImageField(default=300, upload_to='', verbose_name='Price'),
            preserve_default=False,
        ),
    ]
