# Generated by Django 3.2.2 on 2021-05-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_customerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('incart', 'incart'), ('placed', 'placed'), ('ontheway', 'ontheway'), ('delevered', 'delevered')], default='s', max_length=20),
            preserve_default=False,
        ),
    ]
